membase core engine: Requeuer Class Reference
Requeuer Class Reference
Public Member Functions
Requeuer (const QueuedItem &qi, std::queue< QueuedItem > *q, StoredValue *v, rel_time_t qd, rel_time_t d, struct EPStats *s)
void callback (std::pair< bool, int64_t > &value)
Method called on callback.
void callback (bool &value)
Method called on callback.
Constructor & Destructor Documentation
Requeuer::Requeuer (const QueuedItem & qi, std::queue< QueuedItem > * q, StoredValue * v, rel_time_t qd, rel_time_t d, struct EPStats * s) [inline]
Member Function Documentation
void Requeuer::callback (bool & value) [inline, virtual]
Method called on callback.
Implements Callback< bool >.
References EPStats::flushFailed, and StoredValue::reDirty().
void Requeuer::callback (std::pair< bool, int64_t > & value) [inline, virtual]
Method called on callback.
Implements Callback< std::pair< bool, int64_t > >.
References EPStats::flushFailed, StoredValue::reDirty(), and StoredValue::setId().
The documentation for this class was generated from the following file:
ep.cc