membase core engine: RCPtr< C > Class Template Reference
RCPtr< C > Class Template Reference
Concurrent reference counted pointer.
#include <atomic.hh>
Public Member Functions
RCPtr (C *init=NULL)
RCPtr (const RCPtr< C > &other)
~RCPtr ()
void reset (C *newValue=NULL)
void reset (const RCPtr< C > &other)
bool cas (RCPtr< C > &oldValue, RCPtr< C > &newValue)
C * get ()
void operator= (RCPtr< C > &other)
C & operator* () const
C * operator-> () const
bool operator! () const
operator bool () const
Detailed Description
template<class C>
class RCPtr< C >
Concurrent reference counted pointer.
Constructor & Destructor Documentation
template<class C> RCPtr< C >::RCPtr (C * init = NULL) [inline]
template<class C> RCPtr< C >::RCPtr (const RCPtr< C > & other) [inline]
template<class C> RCPtr< C >::~RCPtr () [inline]
Member Function Documentation
template<class C> bool RCPtr< C >::cas (RCPtr< C > & oldValue, RCPtr< C > & newValue) [inline]
template<class C> C* RCPtr< C >::get () [inline]
Referenced by RCPtr< VBucketHolder >::cas().
template<class C> RCPtr< C >::operator bool () const [inline]
template<class C> bool RCPtr< C >::operator! () const [inline]
template<class C> C& RCPtr< C >::operator* () const [inline]
template<class C> C* RCPtr< C >::operator-> () const [inline]
template<class C> void RCPtr< C >::operator= (RCPtr< C > & other) [inline]
template<class C> void RCPtr< C >::reset (const RCPtr< C > & other) [inline]
template<class C> void RCPtr< C >::reset (C * newValue = NULL) [inline]
Referenced by VBucketHolder::addBucket(), LoadStorageKVPairCallback::callback(), LoadStorageKVPairCallback::initVBucket(), RCPtr< VBucketHolder >::operator=(), and VBucketHolder::removeBucket().
The documentation for this class was generated from the following file:
atomic.hh