membase core engine: Callback< RV > Class Template Reference
Callback< RV > Class Template Reference
Interface for callbacks from storage APIs.
#include <callbacks.hh>
Public Member Functions
virtual ~Callback ()
virtual void callback (RV &value)=0
Method called on callback.
virtual void setStatus (int status)
virtual int getStatus ()
Detailed Description
template<typename RV>
class Callback< RV >
Interface for callbacks from storage APIs.
Constructor & Destructor Documentation
template<typename RV> virtual Callback< RV >::~Callback () [inline, virtual]
Member Function Documentation
template<typename RV> virtual void Callback< RV >::callback (RV & value) [pure virtual]
Method called on callback.
Implemented in RememberingCallback< T >, Requeuer, LoadStorageKVPairCallback, BoolCallback, BoolPairCallback, and LookupCallback.
Referenced by StrategicSqlite3::del(), StrategicSqlite3::dump(), StrategicSqlite3::get(), and EventuallyPersistentStore::getLocked().
template<typename RV> virtual int Callback< RV >::getStatus () [inline, virtual]
template<typename RV> virtual void Callback< RV >::setStatus (int status) [inline, virtual]
The documentation for this class was generated from the following file:
callbacks.hh