membase core engine: GetlExtension Class Reference
GetlExtension Class Reference
#include <ep_extension.h>
Public Member Functions
GetlExtension (EventuallyPersistentStore *kvstore, GET_SERVER_API get_server_api)
void initialize ()
bool executeGetl (int argc, token_t *argv, void *cookie, bool(*response_handler)(const void *, int, const char *))
Constructor & Destructor Documentation
GetlExtension::GetlExtension (EventuallyPersistentStore * kvstore, GET_SERVER_API get_server_api)
Member Function Documentation
bool GetlExtension::executeGetl (int argc, token_t * argv, void * cookie, bool(*)(const void *, int, const char *) response_handler)
Referenced by ext_execute().
void GetlExtension::initialize ()
References ext_abort(), ext_accept(), ext_execute(), ext_get_name(), and getLogger().
Referenced by EventuallyPersistentEngine::initialize().
The documentation for this class was generated from the following files:
ep_extension.h
ep_extension.cc