membase core engine: SpinLockHolder Class Reference
SpinLockHolder Class Reference
Safe LockHolder for SpinLock instances.
#include <atomic.hh>
Public Member Functions
SpinLockHolder (SpinLock *theLock)
~SpinLockHolder ()
void lock ()
void unlock ()
Detailed Description
Safe LockHolder for SpinLock instances.
Constructor & Destructor Documentation
SpinLockHolder::SpinLockHolder (SpinLock * theLock) [inline]
References lock().
SpinLockHolder::~SpinLockHolder () [inline]
References unlock().
Member Function Documentation
void SpinLockHolder::lock () [inline]
References SpinLock::acquire().
Referenced by SpinLockHolder().
void SpinLockHolder::unlock () [inline]
References SpinLock::release().
Referenced by RCPtr< VBucketHolder >::cas(), and ~SpinLockHolder().
The documentation for this class was generated from the following file:
atomic.hh