membase core engine: Flusher Class Reference
Flusher Class Reference
#include <flusher.hh>
Public Member Functions
Flusher (EventuallyPersistentStore *st, Dispatcher *d)
~Flusher ()
bool stop ()
void wait ()
bool pause ()
bool resume ()
void initialize (TaskId)
void start (void)
void wake (void)
bool step (Dispatcher &, TaskId)
bool transition_state (enum flusher_state to)
enum flusher_state state () const
const char * stateName () const
Constructor & Destructor Documentation
Flusher::Flusher (EventuallyPersistentStore * st, Dispatcher * d) [inline]
Flusher::~Flusher () [inline]
References stop(), and wait().
Member Function Documentation
void Flusher::initialize (TaskId tid)
References getLogger(), running, store(), and transition_state().
Referenced by step().
bool Flusher::pause (void)
References pausing, and transition_state().
Referenced by EventuallyPersistentStore::pauseFlusher().
bool Flusher::resume (void)
References running, and transition_state().
Referenced by EventuallyPersistentStore::resumeFlusher().
void Flusher::start (void)
Referenced by EventuallyPersistentStore::startFlusher().
enum flusher_state Flusher::state () const
Referenced by EventuallyPersistentEngine::initialize(), and setVbucket().
const char * Flusher::stateName () const
Referenced by EventuallyPersistentEngine::startFlusher(), step(), EventuallyPersistentEngine::stopFlusher(), and transition_state().
bool Flusher::step (Dispatcher & d, TaskId tid)
References getLogger(), initialize(), initializing, paused, pausing, running, Dispatcher::snooze(), stateName(), stopped, stopping, store(), and transition_state().
Referenced by FlusherStepper::callback().
bool Flusher::stop (void)
References stopping, and transition_state().
Referenced by EventuallyPersistentStore::stopFlusher(), and ~Flusher().
bool Flusher::transition_state (enum flusher_state to)
References Dispatcher::cancel(), getLogger(), stateName(), and validTransition().
Referenced by initialize(), pause(), resume(), step(), and stop().
void Flusher::wait (void)
References stopped.
Referenced by EventuallyPersistentStore::stopFlusher(), and ~Flusher().
void Flusher::wake (void)
References Dispatcher::wake().
The documentation for this class was generated from the following files:
flusher.hh
flusher.cc