membase core engine: SpinLock Class Reference
SpinLock Class Reference
A lighter-weight, smaller lock than a mutex.
#include <atomic.hh>
Public Member Functions
SpinLock ()
bool tryAcquire ()
void acquire ()
void release ()
Detailed Description
A lighter-weight, smaller lock than a mutex.
This is primarily useful when contention is rare.
Constructor & Destructor Documentation
SpinLock::SpinLock () [inline]
Member Function Documentation
void SpinLock::acquire () [inline]
References tryAcquire().
Referenced by SpinLockHolder::lock().
void SpinLock::release () [inline]
Referenced by SpinLockHolder::unlock().
bool SpinLock::tryAcquire () [inline]
Referenced by acquire().
The documentation for this class was generated from the following file:
atomic.hh