membase core engine: Blob Class Reference
Blob Class Reference
A blob is a minimal sized storage for data up to 2^32 bytes long.
#include <item.hh>
Public Member Functions
const char * getData () const
Get the pointer to the contents of this Blob.
size_t length () const
Get the length of this Blob.
const std::string to_s () const
Get a std::string representation of this blob.
void operator delete (void *p)
Static Public Member Functions
static Blob * New (const char *start, const size_t len)
Create a new Blob holding the given data.
static Blob * New (const std::string &s)
Create a new Blob holding the contents of the given string.
static Blob * New (const size_t len, const char c)
Create a new Blob pre-filled with the given character.
Detailed Description
A blob is a minimal sized storage for data up to 2^32 bytes long.
Member Function Documentation
const char* Blob::getData () const [inline]
Get the pointer to the contents of this Blob.
size_t Blob::length () const [inline]
Get the length of this Blob.
static Blob* Blob::New (const std::string & s) [inline, static]
Create a new Blob holding the contents of the given string.
Parameters:
s the string whose contents go into the blob
Returns:
the new Blob instance
References New().
static Blob* Blob::New (const char * start, const size_t len) [inline, static]
Create a new Blob holding the given data.
Parameters:
start the beginning of the data to copy into this blob
len the amount of data to copy in
Returns:
the new Blob instance
Referenced by Item::append(), New(), Item::prepend(), and EventuallyPersistentEngine::tapNotify().
static Blob* Blob::New (const size_t len, const char c) [inline, static]
Create a new Blob pre-filled with the given character.
Parameters:
len the size of the blob
c the character to fill the blob with
Returns:
the new Blob instance
void Blob::operator delete (void * p) [inline]
const std::string Blob::to_s () const [inline]
Get a std::string representation of this blob.
The documentation for this class was generated from the following file:
item.hh