membase core engine: StrategicSqlite3 Class Reference
StrategicSqlite3 Class Reference
#include <sqlite-kvstore.hh>
Public Member Functions
StrategicSqlite3 (SqliteStrategy *s)
Construct an instance of sqlite with the given database name.
~StrategicSqlite3 ()
Cleanup.
void reset ()
Reset database to a clean state.
void begin ()
Begin a transaction (if not already in one).
bool commit ()
Commit a transaction (unless not currently in one).
void rollback ()
Rollback a transaction (unless not currently in one).
void set (const Item &item, Callback< std::pair< bool, int64_t > > &cb)
Overrides set().
void get (const std::string &key, uint16_t vbucket, Callback< GetValue > &cb)
Overrides get().
void del (const std::string &key, uint16_t vbucket, Callback< bool > &cb)
Overrides del().
bool delVBucket (uint16_t vbucket)
bool setVBState (uint16_t vbucket, const std::string &to)
std::map< uint16_t, std::string > listPersistedVbuckets (void)
void dump (Callback< GetValue > &cb)
Overrides dump.
Constructor & Destructor Documentation
StrategicSqlite3::StrategicSqlite3 (SqliteStrategy * s) [inline]
Construct an instance of sqlite with the given database name.
StrategicSqlite3::~StrategicSqlite3 () [inline]
Cleanup.
Member Function Documentation
void StrategicSqlite3::begin () [inline]
Begin a transaction (if not already in one).
bool StrategicSqlite3::commit () [inline]
Commit a transaction (unless not currently in one).
Returns false if the commit fails.
void StrategicSqlite3::del (const std::string & key, uint16_t vbucket, Callback< bool > & cb)
Overrides del().
References PreparedStatement::bind(), Callback< RV >::callback(), Statements::del(), PreparedStatement::execute(), SqliteStrategy::forKey(), and PreparedStatement::reset().
bool StrategicSqlite3::delVBucket (uint16_t vbucket)
References SqliteStrategy::allStatements(), PreparedStatement::bind(), PreparedStatement::execute(), SqliteStrategy::getDelVBucketStateST(), and PreparedStatement::reset().
void StrategicSqlite3::dump (Callback< GetValue > & cb)
Overrides dump.
References SqliteStrategy::allStatements(), Callback< RV >::callback(), PreparedStatement::column_blob(), PreparedStatement::column_bytes(), PreparedStatement::column_int(), PreparedStatement::column_int64(), PreparedStatement::fetch(), and PreparedStatement::reset().
Referenced by EventuallyPersistentStore::warmup().
void StrategicSqlite3::get (const std::string & key, uint16_t vbucket, Callback< GetValue > & cb)
Overrides get().
References PreparedStatement::bind(), Callback< RV >::callback(), PreparedStatement::column_blob(), PreparedStatement::column_bytes(), PreparedStatement::column_int(), PreparedStatement::fetch(), SqliteStrategy::forKey(), PreparedStatement::reset(), and Statements::sel().
Referenced by GetCallback::callback().
std::map< uint16_t, std::string > StrategicSqlite3::listPersistedVbuckets (void)
References PreparedStatement::column(), PreparedStatement::column_int(), PreparedStatement::fetch(), SqliteStrategy::getGetVBucketStateST(), and PreparedStatement::reset().
Referenced by EventuallyPersistentStore::warmup().
void StrategicSqlite3::reset ()
Reset database to a clean state.
References SqliteStrategy::destroyTables(), and rollback().
void StrategicSqlite3::rollback () [inline]
Rollback a transaction (unless not currently in one).
Referenced by reset().
void StrategicSqlite3::set (const Item & item, Callback< std::pair< bool, int64_t > > & cb)
Overrides set().
References Item::getId().
bool StrategicSqlite3::setVBState (uint16_t vbucket, const std::string & to)
References PreparedStatement::bind(), PreparedStatement::execute(), SqliteStrategy::getSetVBucketStateST(), and PreparedStatement::reset().
The documentation for this class was generated from the following files:
sqlite-kvstore.hh
sqlite-kvstore.cc