membase core engine: MultiDBSqliteStrategy Class Reference
MultiDBSqliteStrategy Class Reference
#include <sqlite-strategies.hh>
Public Member Functions
MultiDBSqliteStrategy (const char *const fn, const char *const finit=NULL, int n=4)
void initTables (void)
void initStatements (void)
void destroyTables (void)
Constructor & Destructor Documentation
MultiDBSqliteStrategy::MultiDBSqliteStrategy (const char *const fn, const char *const finit = NULL, int n = 4) [inline]
Member Function Documentation
void MultiDBSqliteStrategy::destroyTables (void) [virtual]
Reimplemented from SqliteStrategy.
References SqliteStrategy::execute().
void MultiDBSqliteStrategy::initStatements (void) [virtual]
Reimplemented from SqliteStrategy.
References SqliteStrategy::db, SqliteStrategy::initMetaStatements(), and SqliteStrategy::statements.
void MultiDBSqliteStrategy::initTables (void) [virtual]
Reimplemented from SqliteStrategy.
References SqliteStrategy::execute(), and SqliteStrategy::filename.
The documentation for this class was generated from the following files:
sqlite-strategies.hh
sqlite-strategies.cc