membase core engine: MultiLockHolder Class Reference
MultiLockHolder Class Reference
RAII lock holder over multiple locks.
#include <locks.hh>
Public Member Functions
MultiLockHolder (Mutex *m, size_t n)
Acquire a series of locks.
~MultiLockHolder ()
void lock ()
Relock the series after having manually unlocked it.
void unlock ()
Manually unlock the series.
Detailed Description
RAII lock holder over multiple locks.
Constructor & Destructor Documentation
MultiLockHolder::MultiLockHolder (Mutex * m, size_t n) [inline]
Acquire a series of locks.
Parameters:
m beginning of an array of locks
n the number of locks to lock
References lock().
MultiLockHolder::~MultiLockHolder () [inline]
References unlock().
Member Function Documentation
void MultiLockHolder::lock () [inline]
Relock the series after having manually unlocked it.
References Mutex::acquire().
Referenced by MultiLockHolder().
void MultiLockHolder::unlock () [inline]
Manually unlock the series.
References Mutex::release().
Referenced by ~MultiLockHolder().
The documentation for this class was generated from the following file:
locks.hh