membase core engine: VBucket Class Reference
VBucket Class Reference
An individual vbucket.
#include <vbucket.hh>
Public Member Functions
VBucket (int i, vbucket_state_t initialState)
~VBucket ()
int getId (void)
vbucket_state_t getState (void)
void setState (vbucket_state_t to, SERVER_CORE_API *core)
const char * getStateString (void)
bool addPendingOp (const void *cookie)
void fireAllOps (SERVER_CORE_API *core, ENGINE_ERROR_CODE code=ENGINE_SUCCESS)
size_t size (void)
Static Public Member Functions
static const char * toString (vbucket_state_t s)
Public Attributes
HashTable ht
Detailed Description
An individual vbucket.
Constructor & Destructor Documentation
VBucket::VBucket (int i, vbucket_state_t initialState) [inline]
VBucket::~VBucket () [inline]
References getLogger().
Member Function Documentation
bool VBucket::addPendingOp (const void * cookie) [inline]
void VBucket::fireAllOps (SERVER_CORE_API * core, ENGINE_ERROR_CODE code = ENGINE_SUCCESS)
Referenced by setState().
int VBucket::getId (void) [inline]
vbucket_state_t VBucket::getState (void) [inline]
const char* VBucket::getStateString (void) [inline]
References toString().
void VBucket::setState (vbucket_state_t to, SERVER_CORE_API * core)
References fireAllOps(), getLogger(), and toString().
size_t VBucket::size (void) [inline]
References ht, HashTableDepthStatVisitor::size, and HashTable::visitDepth().
static const char* VBucket::toString (vbucket_state_t s) [inline, static]
Referenced by VBucketHolder::addBucket(), getStateString(), setState(), EventuallyPersistentStore::setVBucketState(), and StatVBucketVisitor::visitBucket().
Member Data Documentation
HashTable VBucket::ht
Referenced by size().
The documentation for this class was generated from the following files:
vbucket.hh
vbucket.cc