membase core engine: EventuallyPersistentStore Class Reference
EventuallyPersistentStore Class Reference
#include <ep.hh>
Public Member Functions
EventuallyPersistentStore (StrategicSqlite3 *t, bool startVb0)
~EventuallyPersistentStore ()
ENGINE_ERROR_CODE set (const Item &item, const void *cookie, bool force=false)
GetValue get (const std::string &key, uint16_t vbucket, const void *cookie)
void getFromUnderlying (const std::string &key, uint16_t vbucket, shared_ptr< Callback< GetValue > > cb)
ENGINE_ERROR_CODE del (const std::string &key, uint16_t vbucket, const void *cookie)
void reset ()
EPStats & getStats ()
void setMinDataAge (int to)
void setQueueAgeCap (int to)
void resetStats (void)
void startDispatcher (void)
void stopFlusher (void)
void startFlusher (void)
bool pauseFlusher (void)
bool resumeFlusher (void)
RCPtr< VBucket > getVBucket (uint16_t vbid)
void setVBucketState (uint16_t vbid, vbucket_state_t state, SERVER_CORE_API *core)
bool deleteVBucket (uint16_t vbid)
void visit (VBucketVisitor &visitor)
void visitDepth (HashTableDepthVisitor &visitor)
size_t getHashSize ()
size_t getHashLocks ()
void warmup ()
int getTxnSize ()
void setTxnSize (int to)
void setTapStats (size_t depth, size_t fetched)
const Flusher * getFlusher ()
bool getKeyStats (const std::string &key, uint16_t vbucket, key_stats &kstats)
bool getLocked (const std::string &key, uint16_t vbucket, Callback< GetValue > &cb, rel_time_t currentTime, uint32_t lockTimeout)
Friends
class Flusher
Constructor & Destructor Documentation
EventuallyPersistentStore::EventuallyPersistentStore (StrategicSqlite3 * t, bool startVb0)
References VBucketMap::addBucket(), DEFAULT_TXN_SIZE, Flusher, setTxnSize(), startDispatcher(), and startFlusher().
EventuallyPersistentStore::~EventuallyPersistentStore ()
References VerifyStoredVisitor::dirty, getVBucket(), Dispatcher::stop(), and stopFlusher().
Member Function Documentation
ENGINE_ERROR_CODE EventuallyPersistentStore::del (const std::string & key, uint16_t vbucket, const void * cookie)
References EPStats::curr_items, getVBucket(), and queue_op_del.
Referenced by EventuallyPersistentEngine::itemDelete().
bool EventuallyPersistentStore::deleteVBucket (uint16_t vbid)
References EPStats::curr_items, Atomic< T >::decr(), VBucketMap::getBucket(), queue_op_vb_flush, and VBucketMap::removeBucket().
Referenced by EventuallyPersistentEngine::deleteVBucket().
GetValue EventuallyPersistentStore::get (const std::string & key, uint16_t vbucket, const void * cookie)
References ep_current_time, and getVBucket().
Referenced by EventuallyPersistentEngine::get().
const Flusher * EventuallyPersistentStore::getFlusher ()
Referenced by EventuallyPersistentEngine::initialize(), EventuallyPersistentEngine::startFlusher(), and EventuallyPersistentEngine::stopFlusher().
void EventuallyPersistentStore::getFromUnderlying (const std::string & key, uint16_t vbucket, shared_ptr< Callback< GetValue > > cb)
References Dispatcher::schedule().
size_t EventuallyPersistentStore::getHashLocks () [inline]
References VBucketMap::getBucket().
size_t EventuallyPersistentStore::getHashSize () [inline]
References VBucketMap::getBucket().
bool EventuallyPersistentStore::getKeyStats (const std::string & key, uint16_t vbucket, key_stats & kstats)
References key_stats::cas, key_stats::data_age, key_stats::dirtied, key_stats::dirty, key_stats::exptime, key_stats::flags, and getVBucket().
bool EventuallyPersistentStore::getLocked (const std::string & key, uint16_t vbucket, Callback< GetValue > & cb, rel_time_t currentTime, uint32_t lockTimeout)
References Callback< RV >::callback(), Item::getCas(), getVBucket(), and Item::setCas().
EPStats& EventuallyPersistentStore::getStats () [inline]
int EventuallyPersistentStore::getTxnSize () [inline]
References Atomic< T >::get().
RCPtr< VBucket > EventuallyPersistentStore::getVBucket (uint16_t vbid)
References VBucketMap::getBucket().
Referenced by del(), get(), getKeyStats(), getLocked(), EventuallyPersistentEngine::getVBucket(), reset(), set(), and ~EventuallyPersistentStore().
bool EventuallyPersistentStore::pauseFlusher (void)
References Flusher::pause().
Referenced by EventuallyPersistentEngine::stopFlusher().
void EventuallyPersistentStore::reset ()
References EPStats::curr_items, VBucketMap::getBuckets(), getVBucket(), and queue_op_flush.
Referenced by EventuallyPersistentEngine::flush(), and EventuallyPersistentEngine::initialize().
void EventuallyPersistentStore::resetStats (void)
References EPStats::commit_time, EPStats::dirtyAge, EPStats::dirtyAgeHighWat, EPStats::flushDuration, EPStats::flushDurationHighWat, Atomic< T >::set(), EPStats::tooOld, and EPStats::tooYoung.
Referenced by EventuallyPersistentEngine::resetStats().
bool EventuallyPersistentStore::resumeFlusher (void)
References Flusher::resume().
Referenced by EventuallyPersistentEngine::startFlusher().
ENGINE_ERROR_CODE EventuallyPersistentStore::set (const Item & item, const void * cookie, bool force = false)
References EPStats::curr_items, Item::getCas(), Item::getKey(), getVBucket(), Item::getVBucketId(), INVALID_CAS, IS_LOCKED, NOMEM, NOT_FOUND, queue_op_set, and WAS_CLEAN.
Referenced by EventuallyPersistentEngine::store(), and EventuallyPersistentEngine::tapNotify().
void EventuallyPersistentStore::setMinDataAge (int to)
References EPStats::min_data_age, and Atomic< T >::set().
Referenced by EventuallyPersistentEngine::setMinDataAge().
void EventuallyPersistentStore::setQueueAgeCap (int to)
References EPStats::queue_age_cap, and Atomic< T >::set().
Referenced by EventuallyPersistentEngine::setQueueAgeCap().
void EventuallyPersistentStore::setTapStats (size_t depth, size_t fetched) [inline]
References Atomic< T >::set(), EPStats::tap_fetched, and EPStats::tap_queue.
void EventuallyPersistentStore::setTxnSize (int to) [inline]
References Atomic< T >::set().
Referenced by EventuallyPersistentStore(), and EventuallyPersistentEngine::setTxnSize().
void EventuallyPersistentStore::setVBucketState (uint16_t vbid, vbucket_state_t state, SERVER_CORE_API * core)
References VBucketMap::addBucket(), VBucketMap::getBucket(), queue_op_vb_set, Dispatcher::schedule(), and VBucket::toString().
Referenced by EventuallyPersistentEngine::setVBucketState(), EventuallyPersistentEngine::tapNotify(), and EventuallyPersistentEngine::walkTapQueue().
void EventuallyPersistentStore::startDispatcher (void)
References Dispatcher::start().
Referenced by EventuallyPersistentStore().
void EventuallyPersistentStore::startFlusher (void)
References Flusher::start().
Referenced by EventuallyPersistentStore().
void EventuallyPersistentStore::stopFlusher (void)
References Flusher::stop(), and Flusher::wait().
Referenced by ~EventuallyPersistentStore().
void EventuallyPersistentStore::visit (VBucketVisitor & visitor) [inline]
References VBucketMap::getBucket(), VBucketMap::getBuckets(), and VBucketVisitor::visitBucket().
Referenced by launch_backfill_thread().
void EventuallyPersistentStore::visitDepth (HashTableDepthVisitor & visitor) [inline]
References VBucketMap::getBucket().
void EventuallyPersistentStore::warmup () [inline]
References StrategicSqlite3::dump(), getLogger(), LoadStorageKVPairCallback::initVBucket(), and StrategicSqlite3::listPersistedVbuckets().
Friends And Related Function Documentation
friend class Flusher [friend]
Referenced by EventuallyPersistentStore().
The documentation for this class was generated from the following files:
ep.hh
ep.cc