membase core engine: common.hh File Reference
common.hh File Reference
#include <cassert>
#include <errno.h>
#include <stdlib.h>
#include <stdint.h>
#include <ctype.h>
#include <inttypes.h>
#include <limits.h>
#include <math.h>
#include <sys/time.h>
#include <memcached/engine.h>
#include "config.h"
#include <memory>
#include <tr1/memory>
Defines
#define UINT16_MAX 65535
#define DISALLOW_COPY_AND_ASSIGN(TypeName)
Functions
EXTENSION_LOGGER_DESCRIPTOR * getLogger (void)
void advance_tv (struct timeval &tv, const double secs)
bool less_tv (const struct timeval &tv1, const struct timeval &tv2)
bool parseUint16 (const char *in, uint16_t *out)
Define Documentation
#define DISALLOW_COPY_AND_ASSIGN (TypeName)
Value:
TypeName(const TypeName&);                  \
    void operator=(const TypeName&)
#define UINT16_MAX 65535
Referenced by parseUint16().
Function Documentation
void advance_tv (struct timeval & tv, const double secs) [inline]
Referenced by SyncObject::wait().
EXTENSION_LOGGER_DESCRIPTOR* getLogger (void)
Referenced by VBucketHolder::addBucket(), EventuallyPersistentEngine::createTapQueue(), SqliteEvaluator::eval(), EventuallyPersistentEngine::handleDisconnect(), Flusher::initialize(), GetlExtension::initialize(), EventuallyPersistentEngine::initialize(), SqliteStrategy::initPragmas(), launch_dispatcher_thread(), Dispatcher::run(), VBucket::setState(), EventuallyPersistentEngine::startFlusher(), EventuallyPersistentEngine::startReplication(), Flusher::step(), Dispatcher::stop(), EventuallyPersistentEngine::stopFlusher(), EventuallyPersistentEngine::stopReplication(), Flusher::transition_state(), EventuallyPersistentEngine::walkTapQueue(), EventuallyPersistentStore::warmup(), and VBucket::~VBucket().
bool less_tv (const struct timeval & tv1, const struct timeval & tv2) [inline]
Referenced by CompareTasks::operator()(), and Dispatcher::run().
bool parseUint16 (const char * in, uint16_t * out) [inline]
References UINT16_MAX.
Referenced by deleteVBucket(), getVbucket(), and setVbucket().