membase core engine: dispatcher.cc File Reference
dispatcher.cc File Reference
#include "dispatcher.hh"
#include <stdexcept>
#include <queue>
#include "common.hh"
#include "locks.hh"
Functions
static void * launch_dispatcher_thread (void *arg)
Function Documentation
static void * launch_dispatcher_thread (void * arg) [static]
References getLogger(), and Dispatcher::run().
Referenced by Dispatcher::start().