membase core engine: ep.cc File Reference
ep.cc File Reference
#include <vector>
#include <time.h>
#include <string.h>
#include <iostream>
#include "ep.hh"
#include <pthread.h>
#include <assert.h>
#include <stdbool.h>
#include <stdlib.h>
#include <stdexcept>
#include <queue>
#include <unistd.h>
#include <set>
#include <memcached/engine.h>
#include "common.hh"
#include <sched.h>
#include "callbacks.hh"
#include "locks.hh"
#include <map>
#include <stdarg.h>
#include <string>
#include <stdio.h>
#include <inttypes.h>
#include "embedded/sqlite3.h"
#include <cstdlib>
#include "sqlite-pst.hh"
#include "config.h"
#include "mutex.hh"
#include "atomic.hh"
#include <climits>
#include <cstring>
#include <algorithm>
#include "item.hh"
#include "dispatcher.hh"
#include <cassert>
#include <sstream>
#include "stored-value.hh"
#include "ep.hh"
#include "sqlite-kvstore.hh"
Classes
class GetCallback
class SetVBStateCallback
class VerifyStoredVisitor
class Requeuer
Functions
static rel_time_t uninitialized_current_time (void)
Variables
rel_time_t(* ep_current_time)() = uninitialized_current_time
Function Documentation
static rel_time_t uninitialized_current_time (void) [static]
Variable Documentation
rel_time_t(* ep_current_time)() = uninitialized_current_time
Referenced by create_instance(), EventuallyPersistentStore::get(), StoredValue::markDirty(), HashTable::set(), HashTable::unlocked_del(), and HashTable::unlocked_find().