membase core engine: ep_engine.h File Reference
ep_engine.h File Reference
#include "locks.hh"
#include "ep.hh"
#include "flusher.hh"
#include "sqlite-kvstore.hh"
#include "ep_extension.h"
#include <memcached/util.h>
#include "tapclient.hh"
#include <cstdio>
#include <map>
#include <list>
#include <sstream>
#include <algorithm>
#include <errno.h>
#include "command_ids.h"
Classes
class BoolCallback
class BoolPairCallback
class LookupCallback
class StatVBucketVisitor
class TapVBucketEvent
The tap stream may include other events than data mutation events, but the data structures in the TapConnection does only store a key for the item to store.
class TapConnection
Class used by the EventuallyPersistentEngine to keep track of all information needed per Tap connection.
class EventuallyPersistentEngine
class BackFillVisitor
VBucketVisitor to backfill a TapConnection.
Defines
#define NUMBER_OF_SHARDS 4
#define DEFAULT_TAP_IDLE_TIMEOUT 600
#define DEFAULT_MIN_DATA_AGE 120
#define DEFAULT_QUEUE_AGE_CAP 900
Functions
ENGINE_ERROR_CODE create_instance (uint64_t interface, GET_SERVER_API get_server_api, ENGINE_HANDLE **handle)
The only public interface to the eventually persistance engine.
void EvpHandleDisconnect (const void *cookie, ENGINE_EVENT_TYPE type, const void *event_data, const void *cb_data)
void * EvpNotifyTapIo (void *arg)
void EvpHandleTapCallback (const void *cookie, ENGINE_EVENT_TYPE type, const void *event_data, const void *cb_data)
void EvpClockHandler (const void *cookie, ENGINE_EVENT_TYPE type, const void *event_data, const void *cb_data)
static void add_casted_stat (const char *k, const char *v, ADD_STAT add_stat, const void *cookie)
static void add_casted_stat (const char *k, uint64_t v, ADD_STAT add_stat, const void *cookie)
template<typename T >
static void add_casted_stat (const char *k, const Atomic< T > &v, ADD_STAT add_stat, const void *cookie)
Define Documentation
#define DEFAULT_MIN_DATA_AGE 120
#define DEFAULT_QUEUE_AGE_CAP 900
#define DEFAULT_TAP_IDLE_TIMEOUT 600
#define NUMBER_OF_SHARDS 4
Referenced by EventuallyPersistentEngine::initialize().
Function Documentation
template<typename T > static void add_casted_stat (const char * k, const Atomic< T > & v, ADD_STAT add_stat, const void * cookie) [inline, static]
References add_casted_stat(), and Atomic< T >::get().
static void add_casted_stat (const char * k, uint64_t v, ADD_STAT add_stat, const void * cookie) [static]
References add_casted_stat(), and vals.
static void add_casted_stat (const char * k, const char * v, ADD_STAT add_stat, const void * cookie) [static]
Referenced by add_casted_stat(), and StatVBucketVisitor::visitBucket().
ENGINE_ERROR_CODE create_instance (uint64_t interface, GET_SERVER_API get_server_api, ENGINE_HANDLE ** handle)
The only public interface to the eventually persistance engine.
Allocate a new instance and initialize it
Parameters:
interface the highest interface the server supports (we only support interface 1)
get_server_api callback function to get the server exported API functions
handle Where to return the new instance
Returns:
ENGINE_SUCCESS on success
References ep_current_time.
void EvpClockHandler (const void * cookie, ENGINE_EVENT_TYPE type, const void * event_data, const void * cb_data)
void EvpHandleDisconnect (const void * cookie, ENGINE_EVENT_TYPE type, const void * event_data, const void * cb_data)
References getHandle(), and EventuallyPersistentEngine::handleDisconnect().
Referenced by EventuallyPersistentEngine::initialize().
void EvpHandleTapCallback (const void * cookie, ENGINE_EVENT_TYPE type, const void * event_data, const void * cb_data)
void* EvpNotifyTapIo (void * arg)