membase core engine: ep_engine.cc File Reference
ep_engine.cc File Reference
#include "config.h"
#include <assert.h>
#include <poll.h>
#include <fcntl.h>
#include <memcached/engine.h>
#include <memcached/protocol_binary.h>
#include "ep_engine.h"
#include "locks.hh"
#include "ep.hh"
#include "flusher.hh"
#include "sqlite-kvstore.hh"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <memcached/extension.h>
#include <memcached/util.h>
#include <sstream>
#include <cstdio>
#include <map>
#include <list>
#include <algorithm>
#include <errno.h>
Classes
class BackFillThreadData
Functions
static EventuallyPersistentEngine * getHandle (ENGINE_HANDLE *handle)
Helper function to avoid typing in the long cast all over the place.
static const engine_info * EvpGetInfo (ENGINE_HANDLE *handle)
static ENGINE_ERROR_CODE EvpInitialize (ENGINE_HANDLE *handle, const char *config_str)
static void EvpDestroy (ENGINE_HANDLE *handle)
static ENGINE_ERROR_CODE EvpItemAllocate (ENGINE_HANDLE *handle, const void *cookie, item **item, const void *key, const size_t nkey, const size_t nbytes, const int flags, const rel_time_t exptime)
static ENGINE_ERROR_CODE EvpItemDelete (ENGINE_HANDLE *handle, const void *cookie, const void *key, const size_t nkey, uint64_t cas, uint16_t vbucket)
static void EvpItemRelease (ENGINE_HANDLE *handle, const void *cookie, item *item)
static ENGINE_ERROR_CODE EvpGet (ENGINE_HANDLE *handle, const void *cookie, item **item, const void *key, const int nkey, uint16_t vbucket)
static ENGINE_ERROR_CODE EvpGetStats (ENGINE_HANDLE *handle, const void *cookie, const char *stat_key, int nkey, ADD_STAT add_stat)
static ENGINE_ERROR_CODE EvpStore (ENGINE_HANDLE *handle, const void *cookie, item *item, uint64_t *cas, ENGINE_STORE_OPERATION operation, uint16_t vbucket)
static ENGINE_ERROR_CODE EvpArithmetic (ENGINE_HANDLE *handle, const void *cookie, const void *key, const int nkey, const bool increment, const bool create, const uint64_t delta, const uint64_t initial, const rel_time_t exptime, uint64_t *cas, uint64_t *result, uint16_t vbucket)
static ENGINE_ERROR_CODE EvpFlush (ENGINE_HANDLE *handle, const void *cookie, time_t when)
static void EvpResetStats (ENGINE_HANDLE *handle, const void *cookie)
static
protocol_binary_response_status stopFlusher (EventuallyPersistentEngine *e, const char **msg)
static
protocol_binary_response_status startFlusher (EventuallyPersistentEngine *e, const char **msg)
static void validate (int v, int l, int h)
static
protocol_binary_response_status setTapParam (EventuallyPersistentEngine *e, const char *keyz, const char *valz, const char **msg)
static
protocol_binary_response_status setFlushParam (EventuallyPersistentEngine *e, const char *keyz, const char *valz, const char **msg)
static
protocol_binary_response_status setParam (EventuallyPersistentEngine *e, protocol_binary_request_header *request, const char **msg)
static
protocol_binary_response_status getVbucket (EventuallyPersistentEngine *e, protocol_binary_request_header *request, const char **msg)
static
protocol_binary_response_status setVbucket (EventuallyPersistentEngine *e, protocol_binary_request_header *request, const char **msg)
static
protocol_binary_response_status deleteVBucket (EventuallyPersistentEngine *e, protocol_binary_request_header *request, const char **msg)
static ENGINE_ERROR_CODE EvpUnknownCommand (ENGINE_HANDLE *handle, const void *cookie, protocol_binary_request_header *request, ADD_RESPONSE response)
static void EvpItemSetCas (ENGINE_HANDLE *handle, item *item, uint64_t cas)
static ENGINE_ERROR_CODE EvpTapNotify (ENGINE_HANDLE *handle, const void *cookie, void *engine_specific, uint16_t nengine, uint8_t ttl, uint16_t tap_flags, tap_event_t tap_event, uint32_t tap_seqno, const void *key, size_t nkey, uint32_t flags, uint32_t exptime, uint64_t cas, const void *data, size_t ndata, uint16_t vbucket)
static tap_event_t EvpTapIterator (ENGINE_HANDLE *handle, const void *cookie, item **itm, void **es, uint16_t *nes, uint8_t *ttl, uint16_t *flags, uint32_t *seqno, uint16_t *vbucket)
static TAP_ITERATOR EvpGetTapIterator (ENGINE_HANDLE *handle, const void *cookie, const void *client, size_t nclient, uint32_t flags, const void *userdata, size_t nuserdata)
void EvpHandleDisconnect (const void *cookie, ENGINE_EVENT_TYPE type, const void *event_data, const void *cb_data)
ENGINE_ERROR_CODE create_instance (uint64_t interface, GET_SERVER_API get_server_api, ENGINE_HANDLE **handle)
The only public interface to the eventually persistance engine.
void * EvpNotifyTapIo (void *arg)
static bool EvpGetItemInfo (ENGINE_HANDLE *handle, const item *item, item_info *item_info)
EXTENSION_LOGGER_DESCRIPTOR * getLogger (void)
static void * launch_backfill_thread (void *arg)
Variables
static SERVER_EXTENSION_API * extensionApi
Function Documentation
ENGINE_ERROR_CODE create_instance (uint64_t interface, GET_SERVER_API get_server_api, ENGINE_HANDLE ** handle)
The only public interface to the eventually persistance engine.
Allocate a new instance and initialize it
Parameters:
interface the highest interface the server supports (we only support interface 1)
get_server_api callback function to get the server exported API functions
handle Where to return the new instance
Returns:
ENGINE_SUCCESS on success
References ep_current_time.
static protocol_binary_response_status deleteVBucket (EventuallyPersistentEngine * e, protocol_binary_request_header * request, const char ** msg) [static]
References EventuallyPersistentEngine::deleteVBucket(), EventuallyPersistentEngine::getVBucket(), and parseUint16().
Referenced by EvpUnknownCommand().
static ENGINE_ERROR_CODE EvpArithmetic (ENGINE_HANDLE * handle, const void * cookie, const void * key, const int nkey, const bool increment, const bool create, const uint64_t delta, const uint64_t initial, const rel_time_t exptime, uint64_t * cas, uint64_t * result, uint16_t vbucket) [static]
References EventuallyPersistentEngine::arithmetic(), and getHandle().
static void EvpDestroy (ENGINE_HANDLE * handle) [static]
References EventuallyPersistentEngine::destroy(), and getHandle().
static ENGINE_ERROR_CODE EvpFlush (ENGINE_HANDLE * handle, const void * cookie, time_t when) [static]
References EventuallyPersistentEngine::flush(), and getHandle().
static ENGINE_ERROR_CODE EvpGet (ENGINE_HANDLE * handle, const void * cookie, item ** item, const void * key, const int nkey, uint16_t vbucket) [static]
References EventuallyPersistentEngine::get(), and getHandle().
static const engine_info* EvpGetInfo (ENGINE_HANDLE * handle) [static]
References getHandle(), and EventuallyPersistentEngine::getInfo().
static bool EvpGetItemInfo (ENGINE_HANDLE * handle, const item * item, item_info * item_info) [static]
References Item::getCas(), Item::getData(), Item::getExptime(), Item::getFlags(), Item::getKey(), Item::getNBytes(), and Item::getNKey().
static ENGINE_ERROR_CODE EvpGetStats (ENGINE_HANDLE * handle, const void * cookie, const char * stat_key, int nkey, ADD_STAT add_stat) [static]
References getHandle(), and EventuallyPersistentEngine::getStats().
static TAP_ITERATOR EvpGetTapIterator (ENGINE_HANDLE * handle, const void * cookie, const void * client, size_t nclient, uint32_t flags, const void * userdata, size_t nuserdata) [static]
References EventuallyPersistentEngine::createTapQueue(), EvpTapIterator(), and getHandle().
void EvpHandleDisconnect (const void * cookie, ENGINE_EVENT_TYPE type, const void * event_data, const void * cb_data)
References getHandle(), and EventuallyPersistentEngine::handleDisconnect().
Referenced by EventuallyPersistentEngine::initialize().
static ENGINE_ERROR_CODE EvpInitialize (ENGINE_HANDLE * handle, const char * config_str) [static]
References getHandle(), and EventuallyPersistentEngine::initialize().
static ENGINE_ERROR_CODE EvpItemAllocate (ENGINE_HANDLE * handle, const void * cookie, item ** item, const void * key, const size_t nkey, const size_t nbytes, const int flags, const rel_time_t exptime) [static]
References getHandle(), and EventuallyPersistentEngine::itemAllocate().
static ENGINE_ERROR_CODE EvpItemDelete (ENGINE_HANDLE * handle, const void * cookie, const void * key, const size_t nkey, uint64_t cas, uint16_t vbucket) [static]
References getHandle(), and EventuallyPersistentEngine::itemDelete().
static void EvpItemRelease (ENGINE_HANDLE * handle, const void * cookie, item * item) [static]
References getHandle(), and EventuallyPersistentEngine::itemRelease().
static void EvpItemSetCas (ENGINE_HANDLE * handle, item * item, uint64_t cas) [static]
void* EvpNotifyTapIo (void * arg)
static void EvpResetStats (ENGINE_HANDLE * handle, const void * cookie) [static]
References getHandle(), and EventuallyPersistentEngine::resetStats().
static ENGINE_ERROR_CODE EvpStore (ENGINE_HANDLE * handle, const void * cookie, item * item, uint64_t * cas, ENGINE_STORE_OPERATION operation, uint16_t vbucket) [static]
References getHandle(), and EventuallyPersistentEngine::store().
static tap_event_t EvpTapIterator (ENGINE_HANDLE * handle, const void * cookie, item ** itm, void ** es, uint16_t * nes, uint8_t * ttl, uint16_t * flags, uint32_t * seqno, uint16_t * vbucket) [static]
References getHandle(), and EventuallyPersistentEngine::walkTapQueue().
Referenced by EvpGetTapIterator().
static ENGINE_ERROR_CODE EvpTapNotify (ENGINE_HANDLE * handle, const void * cookie, void * engine_specific, uint16_t nengine, uint8_t ttl, uint16_t tap_flags, tap_event_t tap_event, uint32_t tap_seqno, const void * key, size_t nkey, uint32_t flags, uint32_t exptime, uint64_t cas, const void * data, size_t ndata, uint16_t vbucket) [static]
References getHandle(), and EventuallyPersistentEngine::tapNotify().
static ENGINE_ERROR_CODE EvpUnknownCommand (ENGINE_HANDLE * handle, const void * cookie, protocol_binary_request_header * request, ADD_RESPONSE response) [static]
References CMD_DEL_VBUCKET, CMD_GET_VBUCKET, CMD_SET_FLUSH_PARAM, CMD_SET_TAP_PARAM, CMD_SET_VBUCKET, CMD_START_PERSISTENCE, CMD_START_REPLICATION, CMD_STOP_PERSISTENCE, CMD_STOP_REPLICATION, deleteVBucket(), getHandle(), getVbucket(), setParam(), setVbucket(), startFlusher(), EventuallyPersistentEngine::startReplication(), stopFlusher(), and EventuallyPersistentEngine::stopReplication().
static EventuallyPersistentEngine* getHandle (ENGINE_HANDLE * handle) [inline, static]
Helper function to avoid typing in the long cast all over the place.
Parameters:
handle pointer to the engine
Returns:
the engine as a class
Referenced by EvpArithmetic(), EvpDestroy(), EvpFlush(), EvpGet(), EvpGetInfo(), EvpGetStats(), EvpGetTapIterator(), EvpHandleDisconnect(), EvpInitialize(), EvpItemAllocate(), EvpItemDelete(), EvpItemRelease(), EvpResetStats(), EvpStore(), EvpTapIterator(), EvpTapNotify(), and EvpUnknownCommand().
EXTENSION_LOGGER_DESCRIPTOR* getLogger (void)
References extensionApi.
Referenced by VBucketHolder::addBucket(), EventuallyPersistentEngine::createTapQueue(), SqliteEvaluator::eval(), EventuallyPersistentEngine::handleDisconnect(), Flusher::initialize(), GetlExtension::initialize(), EventuallyPersistentEngine::initialize(), SqliteStrategy::initPragmas(), launch_dispatcher_thread(), Dispatcher::run(), VBucket::setState(), EventuallyPersistentEngine::startFlusher(), EventuallyPersistentEngine::startReplication(), Flusher::step(), Dispatcher::stop(), EventuallyPersistentEngine::stopFlusher(), EventuallyPersistentEngine::stopReplication(), Flusher::transition_state(), EventuallyPersistentEngine::walkTapQueue(), EventuallyPersistentStore::warmup(), and VBucket::~VBucket().
static protocol_binary_response_status getVbucket (EventuallyPersistentEngine * e, protocol_binary_request_header * request, const char ** msg) [static]
References EventuallyPersistentEngine::getVBucket(), and parseUint16().
Referenced by EvpUnknownCommand().
static void* launch_backfill_thread (void * arg) [static]
References BackFillVisitor::apply(), BackFillThreadData::bfv, BackFillThreadData::epstore, and EventuallyPersistentStore::visit().
Referenced by EventuallyPersistentEngine::queueBackfill().
static protocol_binary_response_status setFlushParam (EventuallyPersistentEngine * e, const char * keyz, const char * valz, const char ** msg) [static]
References MAX_DATA_AGE_PARAM, MAX_TXN_SIZE, EventuallyPersistentEngine::setMinDataAge(), EventuallyPersistentEngine::setQueueAgeCap(), EventuallyPersistentEngine::setTxnSize(), and validate().
Referenced by setParam().
static protocol_binary_response_status setParam (EventuallyPersistentEngine * e, protocol_binary_request_header * request, const char ** msg) [static]
References CMD_SET_FLUSH_PARAM, CMD_SET_TAP_PARAM, setFlushParam(), and setTapParam().
Referenced by EvpUnknownCommand().
static protocol_binary_response_status setTapParam (EventuallyPersistentEngine * e, const char * keyz, const char * valz, const char ** msg) [static]
References EventuallyPersistentEngine::setTapPeer().
Referenced by setParam().
static protocol_binary_response_status setVbucket (EventuallyPersistentEngine * e, protocol_binary_request_header * request, const char ** msg) [static]
References parseUint16(), EventuallyPersistentEngine::setVBucketState(), and Flusher::state().
Referenced by EvpUnknownCommand().
static protocol_binary_response_status startFlusher (EventuallyPersistentEngine * e, const char ** msg) [static]
References EventuallyPersistentEngine::startFlusher().
Referenced by EvpUnknownCommand().
static protocol_binary_response_status stopFlusher (EventuallyPersistentEngine * e, const char ** msg) [static]
References EventuallyPersistentEngine::stopFlusher().
Referenced by EvpUnknownCommand().
static void validate (int v, int l, int h) [static]
Referenced by setFlushParam().
Variable Documentation
SERVER_EXTENSION_API* extensionApi [static]
Referenced by getLogger().