membase core engine: ep_extension.cc File Reference
ep_extension.cc File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "ep_extension.h"
#include <memcached/extension.h>
#include <memcached/util.h>
Defines
#define ITEM_LOCK_TIMEOUT 15
#define MAX_KEY_LEN 250
Typedefs
typedef bool(* RESPONSE_HANDLER_T)(const void *, int, const char *)
Functions
static GetlExtension * getExtension (const void *cookie)
static const char * ext_get_name (const void *cmd_cookie)
static bool ext_execute (const void *cmd_cookie, const void *cookie, int argc, token_t *argv, RESPONSE_HANDLER_T response_handler)
static bool ext_accept (const void *cmd_cookie, void *cookie, int argc, token_t *argv, size_t *ndata, char **ptr)
static void ext_abort (const void *cmd_cookie, const void *cookie)
Define Documentation
#define ITEM_LOCK_TIMEOUT 15
#define MAX_KEY_LEN 250
Typedef Documentation
typedef bool(* RESPONSE_HANDLER_T)(const void *, int, const char *)
Function Documentation
static void ext_abort (const void * cmd_cookie, const void * cookie) [static]
Referenced by GetlExtension::initialize().
static bool ext_accept (const void * cmd_cookie, void * cookie, int argc, token_t * argv, size_t * ndata, char ** ptr) [static]
Referenced by GetlExtension::initialize().
static bool ext_execute (const void * cmd_cookie, const void * cookie, int argc, token_t * argv, RESPONSE_HANDLER_T response_handler) [static]
References GetlExtension::executeGetl(), and getExtension().
Referenced by GetlExtension::initialize().
static const char* ext_get_name (const void * cmd_cookie) [static]
Referenced by GetlExtension::initialize().
static GetlExtension* getExtension (const void * cookie) [static]
Referenced by ext_execute().